# fly.toml app configuration file generated for recipemod on 2023-08-12T11:29:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "recipemod"
primary_region = "iad"

[build]
builder = "paketobuildpacks/builder:base"

[env]
PORT = "8080"
SECRET_KEY = "fskldfsdfgsdfg"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]
